services:
  - type: web
    name: tracuumst
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
