[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "Nunito"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
